LoadModule fuzztrace_module modules/mod_fuzztrace.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ServerName localhost

<Location />
    Require all granted
</Location>

# DENY ALL proxy requests
<Proxy *>
    Require all denied
</Proxy>

ProxyPass /pp http://backend:80/api
<Location /sh>
    SetHandler "proxy:http://backend:80"
</Location>

<Location /health>
    Require all granted
</Location>
<Location /fuzztrace>
    Require all granted
</Location>
