LoadModule fuzztrace_module modules/mod_fuzztrace.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ServerName localhost

<Location />
    Require all granted
</Location>

<Location /admin>
    Require all denied
</Location>

ProxyPass /pp-ajp ajp://172.18.0.52:8009/app
ProxyPass /pp-http http://backend:80/api

<Location /sh-ajp>
    SetHandler "proxy:ajp://172.18.0.52:8009/app"
</Location>

<Location /sh-http>
    SetHandler "proxy:http://backend:80/api"
</Location>

<Location /health>
    Require all granted
</Location>
<Location /fuzztrace>
    Require all granted
</Location>
