http_port 8080
cache_peer backend parent 8081 0 no-query originserver name=be
acl all src all
http_access allow all
cache_peer_access be allow all
forwarded_for on
via off
cache deny all
relaxed_header_parser on
