"""Apache Confusion differential fuzzing target.

Uses RAW SOCKET HTTP to send URLs exactly as generated by the mutator,
bypassing client-side URL normalization (requests/urllib).  This is
critical — encoded slashes, traversals, null bytes, etc. must reach
Apache unmodified.

Also implements Confused Deputy mode: for each mutated URL, first
verifies that the canonical deny still works, then tests the mutation.

Usage (standalone):
    echo "/..;/admin/" | python targets/apache_confusion_target.py --port 9101

Usage (persistent module via wrapper):
    python targets/persistent_wrapper.py targets/apache_confusion_target_module.py
"""

from __future__ import annotations

import json
import socket
import sys


class RawHttpClient:
    """Persistent raw TCP connection to Apache — no URL normalization."""

    __slots__ = ("_host", "_port", "_sock")

    def __init__(self, host: str, port: int) -> None:
        self._host = host
        self._port = port
        self._sock: socket.socket | None = None

    def _connect(self) -> None:
        if self._sock is not None:
            return
        self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._sock.settimeout(3)
        self._sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        self._sock.connect((self._host, self._port))

    def _reconnect(self) -> None:
        self.close()
        self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._sock.settimeout(3)
        self._sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        self._sock.connect((self._host, self._port))

    def close(self) -> None:
        if self._sock is not None:
            try:
                self._sock.close()
            except OSError:
                pass
            self._sock = None

    def request(
        self,
        raw_path: str,
        method: str = "GET",
        extra_headers: dict[str, str] | None = None,
        body: bytes | None = None,
    ) -> tuple[int, dict[str, str], str]:
        """Send HTTP request with raw_path verbatim. Returns (status, headers, body).

        Supports arbitrary methods (GET, PROPFIND, OPTIONS, etc.) and
        custom headers for header-based confusion testing.
        """
        lines = [
            f"{method} {raw_path} HTTP/1.1",
            f"Host: {self._host}:{self._port}",
            "User-Agent: fuzztrace/1.0",
            "Connection: keep-alive",
        ]
        if extra_headers:
            for k, v in extra_headers.items():
                lines.append(f"{k}: {v}")
        if body is not None:
            lines.append(f"Content-Length: {len(body)}")
        lines.append("")
        lines.append("")
        req = "\r\n".join(lines).encode("latin-1", errors="replace")
        if body is not None:
            req += body

        for attempt in range(2):
            try:
                self._connect()
                self._sock.sendall(req)
                return self._parse_response()
            except (ConnectionError, OSError, socket.timeout):
                self._reconnect()
                if attempt == 1:
                    raise

        return -1, {}, ""  # unreachable

    def _parse_response(self) -> tuple[int, dict[str, str], str]:
        """Parse HTTP/1.1 response from socket."""
        buf = b""
        # Read until \r\n\r\n (end of headers)
        while b"\r\n\r\n" not in buf:
            chunk = self._sock.recv(8192)
            if not chunk:
                raise ConnectionError("connection closed")
            buf += chunk
            if len(buf) > 65536:
                raise ValueError("headers too large")

        header_end = buf.index(b"\r\n\r\n")
        header_bytes = buf[:header_end]
        body_start = buf[header_end + 4:]

        # Parse status line
        lines = header_bytes.split(b"\r\n")
        status_line = lines[0].decode("latin-1", errors="replace")
        parts = status_line.split(" ", 2)
        status = int(parts[1]) if len(parts) >= 2 else 0

        # Parse headers
        headers: dict[str, str] = {}
        for line in lines[1:]:
            if b":" in line:
                k, v = line.split(b":", 1)
                headers[k.strip().decode("latin-1").lower()] = (
                    v.strip().decode("utf-8", errors="replace")
                )

        # Read body based on Content-Length or chunked
        content_length = int(headers.get("content-length", "0"))
        body = body_start
        if content_length > 0:
            remaining = content_length - len(body)
            while remaining > 0:
                chunk = self._sock.recv(min(remaining, 8192))
                if not chunk:
                    break
                body += chunk
                remaining -= len(chunk)
        elif "chunked" in headers.get("transfer-encoding", ""):
            body = self._read_chunked(body)

        return status, headers, body.decode("utf-8", errors="replace")

    def _read_chunked(self, initial: bytes) -> bytes:
        """Read chunked transfer-encoding body."""
        buf = initial
        result = b""
        while True:
            # Find chunk size line
            while b"\r\n" not in buf:
                chunk = self._sock.recv(4096)
                if not chunk:
                    return result
                buf += chunk
            line_end = buf.index(b"\r\n")
            size_str = buf[:line_end].decode("latin-1").strip().split(";")[0]
            chunk_size = int(size_str, 16)
            buf = buf[line_end + 2:]
            if chunk_size == 0:
                break
            # Read chunk data
            while len(buf) < chunk_size + 2:
                more = self._sock.recv(4096)
                if not more:
                    return result + buf[:chunk_size]
                buf += more
            result += buf[:chunk_size]
            buf = buf[chunk_size + 2:]  # skip \r\n after chunk
        return result


# ── Shared session cache ─────────────────────────────────────────
_clients: dict[int, RawHttpClient] = {}


def _make_session(port: int) -> RawHttpClient:
    """Get or create a raw HTTP client for the given port."""
    if port not in _clients:
        _clients[port] = RawHttpClient("127.0.0.1", port)
    return _clients[port]


# ── Protected content markers ────────────────────────────────────
_PROTECTED_MARKERS = (
    "admin area", "secret", "internal config",
    "should be protected", "should never be exposed",
    "access control bypass",
)


def query_apache(session: RawHttpClient, url_path: str) -> dict:
    """Send URL to Apache via raw socket and parse mod_fuzztrace response.

    The URL is sent VERBATIM — no encoding, normalization, or escaping.
    """
    if not url_path.startswith("/"):
        url_path = "/" + url_path

    try:
        status, headers, body = session.request(url_path)
    except Exception as e:
        return {"error": str(e), "status_code": -1}

    # Parse X-FuzzTrace header
    trace_raw = headers.get("x-fuzztrace", "")
    if not trace_raw:
        return {
            "error": "no X-FuzzTrace header",
            "status_code": status,
            "served_protected_content": _check_protected(body),
            "body_marker": _find_marker(body),
        }

    try:
        trace = json.loads(trace_raw)
    except (json.JSONDecodeError, ValueError) as e:
        return {
            "error": f"bad trace JSON: {e}",
            "status_code": status,
            "served_protected_content": _check_protected(body),
            "body_marker": _find_marker(body),
        }

    phases = trace.get("phases", {})

    def _get(phase_name: str, field: str) -> str:
        phase = phases.get(phase_name, {})
        val = phase.get(field)
        return val if val is not None else ""

    uri_translate = _get("translate", "uri")
    uri_access = _get("access_check", "uri")
    uri_fixup = _get("fixup", "uri")
    uri_handler = _get("handler_phase", "uri")

    fn_access = _get("access_check", "filename")
    fn_handler = _get("handler_phase", "filename")

    handler_access = _get("access_check", "handler")
    handler_handler = _get("handler_phase", "handler")

    path_info_access = _get("access_check", "path_info")
    path_info_handler = _get("handler_phase", "path_info")

    final_handler = trace.get("final_handler", "")

    # Derived confusion signals
    uri_changed = uri_access != uri_handler and uri_access != ""
    fn_changed = fn_access != fn_handler and fn_access != ""
    handler_changed = handler_access != handler_handler and handler_access != ""
    acl_matches = not fn_changed

    # Body content heuristic
    served_protected = _check_protected(body)
    body_marker = _find_marker(body)

    # Confused Deputy signal: filename crossed into denied directory?
    fn_crossed_denied = False
    if fn_changed:
        denied_dirs = ("/admin", "/internal")
        fn_ac_in_denied = any(d in fn_access for d in denied_dirs)
        fn_h_in_denied = any(d in fn_handler for d in denied_dirs)
        if not fn_ac_in_denied and fn_h_in_denied:
            fn_crossed_denied = True

    return {
        # Raw phase values
        "uri_at_translate": uri_translate,
        "uri_at_access_check": uri_access,
        "uri_at_fixup": uri_fixup,
        "uri_at_handler": uri_handler,
        "filename_at_access_check": fn_access,
        "filename_at_handler": fn_handler,
        "handler_at_access_check": handler_access,
        "handler_at_handler": handler_handler,
        "path_info_at_access_check": path_info_access,
        "path_info_at_handler": path_info_handler,
        "status_code": status,
        "final_handler": final_handler,
        # Derived confusion signals
        "uri_changed_post_access": uri_changed,
        "filename_changed_post_access": fn_changed,
        "handler_changed_post_access": handler_changed,
        "access_check_target_matches_handler_target": acl_matches,
        # Confused Deputy signals
        "filename_crossed_into_denied": fn_crossed_denied,
        "served_protected_content": served_protected,
        "body_marker": body_marker,
    }


def _check_protected(body: str) -> bool:
    bl = body.lower()
    return any(m in bl for m in _PROTECTED_MARKERS)


def _find_marker(body: str) -> str:
    bl = body.lower()
    for m in _PROTECTED_MARKERS:
        if m in bl:
            return m
    return ""


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Apache confusion target")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("input_file", nargs="?", default=None,
                        help="Input file (reads URL from file instead of stdin)")
    args = parser.parse_args()

    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    client = _make_session(args.port)

    if args.input_file:
        # File-based input (for ProcessTarget {input} mode)
        from pathlib import Path
        url_path = Path(args.input_file).read_text(encoding="utf-8", errors="replace").strip()
        if url_path:
            result = query_apache(client, url_path)
            sys.stdout.write(json.dumps(result, ensure_ascii=False) + "\n")
            sys.stdout.flush()
    else:
        # Stdin-based input (for manual/persistent mode)
        for line in sys.stdin:
            url_path = line.strip()
            if not url_path:
                continue
            result = query_apache(client, url_path)
            sys.stdout.write(json.dumps(result, ensure_ascii=False) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
